= C++ example project manually scanned on SonarQube


It is very easy to manually analyze a C, C++ and Objective-C project with SonarQube:

. Create a `sonar-project.properties` file to store your configuration
.. Add a projectKey of your project
.. https://docs.sonarqube.org/latest/user-guide/user-token/[Generate a unique token] and set it as "sonar.login" (`SONARQUBE_TOKEN` in this example project)
.. Set `sonar.host.url` to your SonarQube server URL
. Download and unzip the Build Wrapper for Windows from {SonarQube URL}/static/cpp/build-wrapper-win-x86.zip
. Add the Build Wrapper to your `%PATH%`
. Download and unzip the https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/[SonarScanner] for Windows
. Add the bin directory of the SonarScanner to your `%PATH%`
. Wrap your clean build command with the Build Wrapper. E.g.: `build-wrapper-win-x86-64.exe --out-dir bw-output MSBuild.exe /t:Rebuild /nodeReuse:false`
. Run `sonar-scanner` specifying:
+
--
.. `-Dsonar.cfamily.compile-commands=bw-output/compile_commands.json` if you are using SonarQube version 10.6 or later
.. `-Dsonar.cfamily.build-wrapper-output=bw-output` if you are using SonarQube version 10.5 or earlier, as build-wrapper did not generate a `compile_commands.json` file before SonarQube 10.6
--
+
Noting that `bw-output` is the directory passed to build wrapper as `--out-dir`

You can take a look at the link:sonar-project.properties[sonar-project.properties] and link:build-analyze.ps1[build-analyze.ps1] to see it in practice. Please be aware that the SonarQube server URL and the `sonar.login` are not completed in this example.

= Documentation
- https://docs.sonarqube.org/latest/analysis/languages/cfamily/[Documentation of the C, C++ and Objective-C plugin and its Build Wrapper]
- https://docs.sonarqube.org/latest/analyzing-source-code/languages/c-family/#analysis-cache[Configuring C, C++ and Objective-C analysis cache]
- https://docs.sonarqube.org/latest/analyzing-source-code/languages/c-family/#parallel-code-scan[Configuring multithreaded execution]


= Windows\MSBuild

A build of the https://github.com/sonarsource-cfamily-examples/code[code repository] on Windows platform using MSBuild build system.

To build the code run:
----
msbuild sonar_scanner_example.vcxproj
----

= Code Description

An example of a flawed C++ code. The https://github.com/sonarsource-cfamily-examples/code[code repository] is meant to be compiled with different build systems using different CI pipelines on Linux, macOS, and Windows.

The https://github.com/sonarsource-cfamily-examples/code[code repository] is forked into other repositories in https://github.com/sonarsource-cfamily-examples[this collection] to add a specific build system, platform, and CI.
The downstream repositories are analyzed either with https://www.sonarqube.org/[SonarQube] or https://sonarcloud.io/[SonarCloud].

You can find examples for:

* https://github.com/sonarsource-cfamily-examples?q=linux[Linux]
* https://github.com/sonarsource-cfamily-examples?q=macos[macOS]
* https://github.com/sonarsource-cfamily-examples?q=windows[Windows]

Using the following build systems:

* https://github.com/sonarsource-cfamily-examples?q=cmake[CMake]
* https://github.com/sonarsource-cfamily-examples?q=autotools[GNU Autotools]
* https://github.com/sonarsource-cfamily-examples?q=xcode[Xcode]
* https://github.com/sonarsource-cfamily-examples?q=msbuild[MSBuild]

Running on the following CI services:

* https://github.com/sonarsource-cfamily-examples?q=azure[Azure DevOps]
* https://github.com/sonarsource-cfamily-examples?q=gh-actions[GitHub Actions]
* https://github.com/sonarsource-cfamily-examples?q=travis[Travis]
* https://github.com/sonarsource-cfamily-examples?q=jenkins[Jenkins]
* https://github.com/sonarsource-cfamily-examples?q=gitlab[GitLab CI]
* https://github.com/sonarsource-cfamily-examples?q=bitbucket[BitBucket Pipelines]
* Additionally, https://github.com/orgs/sonarsource-cfamily-examples/repositories?q=otherci[generic examples] demonstrate integration with other CIs and https://github.com/orgs/sonarsource-cfamily-examples/repositories?q=manual[manual-configuration examples] should help you if you are running locally.

Configured for analysis on:

* https://github.com/sonarsource-cfamily-examples?q=-sq[SonarQube]
* https://github.com/sonarsource-cfamily-examples?q=-sc[SonarCloud]

You can find also a few examples demonstrating:

* https://github.com/orgs/sonarsource-cfamily-examples/repositories?q=compdb[The use of Compilation Database (compile_commands.json)]
* https://github.com/orgs/sonarsource-cfamily-examples/repositories?q=topic%3Acoverage[Test coverage]


See link:./examples-structure.adoc[examples-structure.adoc] for a description of the structure of https://github.com/sonarsource-cfamily-examples[this GitHub organization] and the relations between its different repositories.
